#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.5 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);

/* macros for defining the mapping between IRQ and events */
#define sct_fsm_IRQ_EVENT_SCT_IRQ (0)

/* Input assignments */
#define sct_fsm_INPUT_Input_pin_0 (0)

/* Capture registers */
#define sct_fsm_CAPTURE_CAPTURE1 LPC_SCT->CAP[1].U
#define sct_fsm_CAPTURE_CAPTURE2 LPC_SCT->CAP[2].U


/* Match register reload macro definitions */
#define sct_fsm_reload_MATCH0(value) do {LPC_SCT->MATCHREL[0].U = value;} while(0)

#endif
